openapi: 3.0.1
info:
  description: |
    ...
  title: Restic Restore Server
  version: 1.0.0
servers:
- url: http://localhost:80
paths:
  /snapshots:
    get:
      description: |
        List all snapshots
      operationId: getSnapshots
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
          description: |
            The urls will be available after about 3 minutes.
      x-eov-operation-handler: controllers/DefaultController
components:
  schemas: {}
