openapi: 3.0.1
info:
  description: |
    ...
  title: Restic Restore Server
  version: 1.0.0
servers:
- url: http://localhost:80
paths:
  /snapshots:
    get:
      description: |
        List all snapshots
      operationId: getSnapshots
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SnapshotList'
          description: |
            List all available snapshots
      x-eov-operation-handler: handlers/DefaultController
  /snapshots/{shortId}/restore:
    get:
      description: |
        Executes an restore based on the **short_id**
      operationId: restoreSnapshot
      parameters:
      - description: Snapshot id Query Parameter.
        explode: false
        in: path
        name: shortId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SnapshotList'
          description: |
            Snapshot restored successfully
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FoundError'
          description: |
            Snapshot id not found
      x-eov-operation-handler: handlers/DefaultController
components:
  parameters:
    shortIdParam:
      description: Snapshot id Query Parameter.
      explode: false
      in: path
      name: shortId
      required: true
      schema:
        type: string
      style: simple
  schemas:
    Error:
      properties:
        message:
          type: string
      required:
      - message
    FoundError:
      properties:
        message:
          example: Not Found
          type: string
      required:
      - message
    ValidationError:
      properties:
        message:
          example: request.query should have required property 'shortId'
          type: string
        errors:
          $ref: '#/components/schemas/ValidationError_errors'
      required:
      - message
      - validationErrors
    SnapshotList:
      additionalProperties: false
      items:
        $ref: '#/components/schemas/Snapshot'
      type: array
    Snapshot:
      additionalProperties: false
      example:
        hostname: f1520eccaf43
        paths:
        - /data
        - /data
        tree: b2325742d7eb352315fda12205883d66dacae46601ecc0067d1f0f94f577ac52
        id: 15051ed1ea1d267c7f82ac0de63c0b1c3eafa4e3b7899f965fd23a50b009b2d6
        short_id: 15051ed1
        time: '"2020-05-29T17:49:00.136672148Z'
        username: root
        tags:
        - test
        - test
      properties:
        id:
          description: ID of the snapshot
          example: 15051ed1ea1d267c7f82ac0de63c0b1c3eafa4e3b7899f965fd23a50b009b2d6
          type: string
        short_id:
          description: Short ID of the snapshot
          example: 15051ed1
          type: string
        time:
          description: Time when the snapshot was taken
          example: '"2020-05-29T17:49:00.136672148Z'
          type: string
        username:
          description: Username of ...
          example: root
          type: string
        hostname:
          description: The Host ???
          example: f1520eccaf43
          type: string
        tree:
          description: The Tree ...
          example: b2325742d7eb352315fda12205883d66dacae46601ecc0067d1f0f94f577ac52
          type: string
        tags:
          description: List of tags
          items:
            example: test
            type: string
          type: array
        paths:
          description: List of tags
          items:
            example: /data
            type: string
          type: array
      required:
      - hostname
      - id
      - paths
      - short_id
      - tags
      - time
      - tree
      - username
      type: object
    ValidationError_errors:
      properties:
        path:
          example: .query.shortId
          type: string
        message:
          example: should have required property 'shortId'
          type: string
        errorCode:
          example: required.openapi.validation
          type: string
