openapi: 3.0.1
info:
  description: |
    ...
  title: Restic Restore Server
  version: 2020-04-04T07:24:59Z
servers:
- url: /
paths:
  /instances:
    get:
      description: |
        Gets details about all running Alfresco instances. Notice as there is no permission context implemented yet you can view all / specific instances with leaving out the userId parameter oder take a userId from another user.
      operationId: getInstances
      parameters:
      - description: User id Query Parameter. Please use you user name from the system.
        explode: true
        in: query
        name: userId
        required: false
        schema:
          $ref: '#/components/schemas/userId'
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InstanceList'
          description: |
            The urls will be available after about 3 minutes.
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthError'
          description: Authorization information is missing or invalid
      tags:
      - instances
      x-amazon-apigateway-request-validator: Validator
components:
  parameters:
    userIdQueryParam:
      description: User id Query Parameter. Please use you user name from the system.
      explode: true
      in: query
      name: userId
      required: false
      schema:
        $ref: '#/components/schemas/userId'
      style: form
  schemas:
    Error:
      properties:
        message:
          type: string
      required:
      - message
    FoundError:
      properties:
        message:
          example: Not Found
          type: string
      required:
      - message
    AuthError:
      properties:
        message:
          example: Unauthorized
          type: string
      required:
      - message
    ValidationError:
      properties:
        message:
          example: Invalid request body
          type: string
        validationErrors:
          example: '[instance value ("terminatedd") not found in enum (possible values:
            ["running","terminated","stopped"])]'
          type: string
      required:
      - message
      - validationErrors
    InstanceList:
      additionalProperties: false
      items:
        $ref: '#/components/schemas/Instance'
      type: array
    Instance:
      additionalProperties: false
      example:
        adminCredentials:
          password: admin
          userName: admin
        alfInstanceId: ew2m
      properties:
        alfInstanceId:
          additionalProperties: false
          description: User Instance Identifier created with node uuid
          example: ew2m
          maxLength: 4
          minLength: 4
          pattern: '[a-z0-9]{4,4}'
          type: object
        status:
          $ref: '#/components/schemas/status'
        adminCredentials:
          $ref: '#/components/schemas/Instance_adminCredentials'
      required:
      - adminCredentials
      - alfInstanceId
      - status
      type: object
    userId:
      additionalProperties: false
      description: Simple user name. Please use your user name from the system.
      example: martin
      maxLength: 64
      minLength: 2
      pattern: '[a-zA-Z0-9]{2,64}'
      type: object
    alfInstanceId:
      additionalProperties: false
      description: User Instance Identifier created with node uuid
      example: ew2m
      maxLength: 4
      minLength: 4
      pattern: '[a-z0-9]{4,4}'
      type: object
    status:
      additionalProperties: false
      description: Shows the current state. Even if your instance is in the running
        state it might take some minutes until the provided url is reachable.
      enum:
      - running
      - terminated
      - stopped
      - pending
      - stopping
      type: object
    Instance_adminCredentials:
      example:
        password: admin
        userName: admin
      properties:
        userName:
          example: admin
          type: string
        password:
          example: admin
          type: string
      required:
      - password
      - userName
