openapi: 3.0.1
info:
  description: |
    ...
  title: Restic Restore Server
  version: 2020-04-04T07:24:59Z
servers:
- url: /
paths:
  /snapshots:
    get:
      description: |
        List all snapshots
      operationId: getSnapshots
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
          description: |
            The urls will be available after about 3 minutes.
components:
  schemas: {}
