# Using version 2 as 3 does not support resource constraint options (cpu_*, mem_* limits) for non swarm mode in Compose
version: "2"

services:
  restic:
    build: .
    environment:
      RESTIC_PASSWORD: test
      RESTIC_TAG: test
      RESTIC_FORGET_ARGS: '--keep-last 10'
      BACKUP_CRON: '* * * * *'
      # MAILX_ARGS: ''
      # RESTIC_REPOSITORY: '' S3 here
      # AWS_ACCESS_KEY_ID: ''
      # AWS_SECRET_ACCESS_KEY: ''
    volumes:
      - ./data:/data
      - ./test-repo/:/mnt/restic
