/*
 * Restic Restore Server
 *
 * ... 
 *
 * API version: 2020-04-04T07:24:59Z
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"
)


// InstancesApiRouter defines the required methods for binding the api requests to a responses for the InstancesApi
// The InstancesApiRouter implementation should parse necessary information from the http request, 
// pass the data to a InstancesApiServicer to perform the required actions, then write the service results to the http response.
type InstancesApiRouter interface { 
	GetInstances(http.ResponseWriter, *http.Request)
}


// InstancesApiServicer defines the api actions for the InstancesApi service
// This interface intended to stay up to date with the openapi yaml used to generate it, 
// while the service implementation can ignored with the .openapi-generator-ignore file 
// and updated with the logic required for the API.
type InstancesApiServicer interface { 
	GetInstances(map[string]interface{}) (interface{}, error)
}
