/*
 * Restic Restore Server
 *
 * ... 
 *
 * API version: 2020-04-04T07:24:59Z
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"errors"
)

// InstancesApiService is a service that implents the logic for the InstancesApiServicer
// This service should implement the business logic for every endpoint for the InstancesApi API. 
// Include any external packages or services that will be required by this service.
type InstancesApiService struct {
}

// NewInstancesApiService creates a default api service
func NewInstancesApiService() InstancesApiServicer {
	return &InstancesApiService{}
}

// GetInstances - 
func (s *InstancesApiService) GetInstances(userId map[string]interface{}) (interface{}, error) {
	// TODO - update GetInstances with the required logic for this service method.
	// Add api_instances_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'GetInstances' not implemented")
}
