/*
 * Restic Restore Server
 *
 * ... 
 *
 * API version: 2020-04-04T07:24:59Z
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"encoding/json"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

// A InstancesApiController binds http requests to an api service and writes the service results to the http response
type InstancesApiController struct {
	service InstancesApiServicer
}

// NewInstancesApiController creates a default api controller
func NewInstancesApiController(s InstancesApiServicer) Router {
	return &InstancesApiController{ service: s }
}

// Routes returns all of the api route for the InstancesApiController
func (c *InstancesApiController) Routes() Routes {
	return Routes{ 
		{
			"GetInstances",
			strings.ToUpper("Get"),
			"/instances",
			c.GetInstances,
		},
	}
}

// GetInstances - 
func (c *InstancesApiController) GetInstances(w http.ResponseWriter, r *http.Request) { 
	query := r.URL.Query()
	userId := query.Get("userId")
	result, err := c.service.GetInstances(userId)
	if err != nil {
		w.WriteHeader(500)
		return
	}
	
	EncodeJSONResponse(result, nil, w)
}
