/*
 * Restic Restore Server
 *
 * ... 
 *
 * API version: 2020-04-04T07:24:59Z
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ValidationError struct {

	Message string `json:"message"`

	ValidationErrors string `json:"validationErrors"`
}
