/**
* Restic Restore Server
* ... 
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.server

import io.ktor.locations.KtorExperimentalLocationsAPI
import io.ktor.locations.Location

object Paths {
    /**
     * 
     * List all snapshots

     */
    @KtorExperimentalLocationsAPI
    @Location("/snapshots") class getSnapshots()

}
